accent = "#20b2aa"
cursor = "#7ec0ee"
foreground = "#d9e6e2"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#80a0ff"

color0 = "#000000"
color1 = "#b22222"
color2 = "#90ee90"
color3 = "#7fff00"
color4 = "#80a0ff"
color5 = "#bf7fff"
color6 = "#00cdcd"
color7 = "#d9e6e2"
color8 = "#3d5d6d"
color9 = "#ff3030"
color10 = "#00ff7f"
color11 = "#b0e2ff"
color12 = "#87cefa"
color13 = "#ab82ff"
color14 = "#40e0d0"
color15 = "#ffffff"
